name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Trigger manual or automated App Runner deployment
        run: |
          echo "Image pushed to ECR: $IMAGE_URI"
          echo "You can now deploy or automate App Runner deployment using CLI or CloudFormation."
